export const architecture = {
  registers: 16,
  memory: 32,
  maxInstructions: 200,
  instructions: [
    'ADD',
    'ADDI',
    'SUB',
    'MUL',
    'DIV',
    'REM',
    'AND',
    'ANDI',
    'OR',
    'ORI',
    'XOR',
    'XORI',
    'SLT',
    'SLTI',
    'SLL',
    'SLR',
    'MOVE',
    'BEQ',
    'BNE',
    'LW',
    'SW',
    'JUMP',
    'NOP'
  ],
  threeRegisterMnemonics: [
    'ADD',
    'SUB',
    'MUL',
    'DIV',
    'REM',
    'AND',
    'OR',
    'XOR',
    'SLT',
    'SLL',
    'SLR'
  ],
  twoRegisterOneConstantMnemonics: ['ADDI', 'ANDI', 'ORI', 'XORI', 'SLTI'],
  twoRegisterMnemonics: ['MOVE'],
  branchMnemonics: ['BEQ', 'BNE'],
  memoryMnemonics: ['LW', 'SW'],
  jumpMnemonics: ['JUMP'],
  nopMnemonics: ['NOP']
};
